### ISSUE TITLE
Various issues with 1.7.10-4.0.0.74

### ISSUE THREAD

**Issue by LemADEC** [Epoxide-MC/Enchanting-Plus#18] opened 2015-12-28 13:42 UTC
I've tried latest version in Bookshelf-1.7.10-1.0.4.172.jar and EnchantingPlus-1.7.10-4.0.0.74.jar and noted few weird things:
- in NEI, the filtering by mod name doesn't work (if I type @ enchan or @ plus, nothing comes up)

- Enchanted scrolls have no effect: right clicking or shift right clicking won't allow me to learn the new enchant. Throwing them on the inscriber has no effect either.

- right clicking the Arcane inscriber gives an achievement but doesn't open any GUI. Dropping items on it or right clicking with items doesn't do much I could see.

- left clicking the Arcana inscriber breaks it instantly without any drops.

- Advanced enchantment table with no bookshelf reports 10 levels available.

Here are the related settings used:
```
settings {
    # If this is true, players will be able to enchant items which are not at full durability. [default: true]
    B:allowDamagedEnchanting=false

    # If this is true, players will be able to disenchant enchanted items they come across. [default: true]
    B:allowDisenchanting=true

    # If true, special information will be written to the Scroll Modifier item tooltips. [default: true]
    B:allowModifierTooltips=true

    # If this is true, players will be able to repair damaged items at the advanced enchanting table, using experience points [default: true]
    B:allowRepairs=true

    # If enabled, players will be able to modify items which are not currently owned by any other player. IE: Dungeon Loot [default: true]
    B:allowUnownedModifications=true

    # If enabled, a custom E+ villager will spawn and generate in villages. [default: true]
    B:allowVillagers=true

    # A list of blacklisted enchantment ids. Each entry should be an integer. [default: ]
    S:blacklistedEnchantments <
     >

    # A list of blacklisted items and blocks. Things in this list won't be enchantable at the eplus table. The format is the same as minecraft's id system. For example, minecraft:chainmail_helmet will prevent chainmail helmets from becoming enchanted. [default: ]
    S:blacklistedItems <
     >

    # A number used when calculated enchantment cost. This number is treated as a % based factor. 0.30 = 30% of the original cost. 1.5 = 150% of the original cost. [range: 0.0 ~ 128.0, default: 1.0]
    S:costFactor=1.0

    # What is the maximum number of enchantments that could be applied at the Enchantment Table? [range: 0 ~ 4096, default: 5]
    I:maxEnchantmentAmount=5

    # The lowest number of bookshelfs required for the table to function properly. [range: 0 ~ 24, default: 5]
    I:minBookshelfs=5

    # The minimum amount of Bookshelfs required to use the enchantment table. [range: 0 ~ 64, default: 5]
    I:minimumBookshelfs=5

    # Should the table restrict the level of effects based on the amount of bookshelves? [default: true]
    B:needBookshelves=true

    # If true, Enchanting Plus will ocasionally write messages to the console. [default: true]
    B:printDebug=true

    # A number used when calculating the repair costs. A higher factor means higher repair costs. [range: 0 ~ 128, default: 5]
    I:repairFactor=5

    # The percent chance that a hostile mob should drop a scroll. Default is 0.01 which is 1% [range: 0.0 ~ 1.0, default: 0.01]
    S:scrollDropRate=0.01

    # If enabled, players will only be able to enchant enchanted items if they enchanted them first. [default: true]
    B:secureItems=true

    # Quest Mode requires that users collect scrolls to unlock enchantments, before they can make use of them at the table. [default: true]
    B:useQuestMode=true

    # A unique ID for the E+ villager. This should almost never need to be changed. [range: -2147483648 ~ 2147483647, default: 935153]
    I:villagerID=935153
}
```

**Comment by darkhax** [comment] 2015-12-28 19:22
I am not sure what the issue with NEI could be caused by. We have an NEI plugin in Bookshelf, however it doesn't touch mod filtering at all. In my testing I could not reproduce this issue. Perhaps it is another mod you have installed, or an issue with your version of NEI which might be newer then mine. I am testing against 1.0.5.118.

The enchanted scrolls must be held down for a few seconds, like a bow or potion. If you are in creative mode it will be instant. 

The Arcane Inscriber does not have a GUI, and can only be used when right clicking with certain items. The first thing you need to do is right click with an enchanted book, and then you can add up to two modifiers to increase the speed and success rate. The list of modifiers include eyes of ender, emeralds, glowstone blocks and a few other things. If you have Wawla installed, you should be able to search the word "scroll" to find which items are considered scroll modifiers. 

Breaking the block instantly, and not getting a drop back is a bug. It will be fixed shortly. 

Right now the minimum bookshelves value in your config file is set to 5. This value is listed twice in the config file which is a bug, however it doesn't impact the game. The description of the config value is also wrong. The way it actually works, is as bonus modifier to the amount of bookshelves at the table. Right now the value is set to 5, so every enchantment table will act as if it has five additional enchantment tables around it. Each enchantment table is equal to 2 additional levels to the max level cap, which is why the max level is 10 when you have no bookshelves. The description for this will also be fixed shortly.

**Comment by LemADEC** [comment] 2015-12-28 20:48
I'm using NotEnoughItems-1.7.10-1.0.5.118 with CodeChickenCore-1.7.10-1.0.7.47-universal, see Arcania craft modpack on Technic launcher for the full set.

I'm now able to learn the enchanted scroll. I would suggest to update the NEI information for it or add a tool tip on how to use it. Also, the particles doesn't show up at the right angle so you've no visual feedback that right clicking the scroll is the right thing to do.

I've tried right clicking an enchanted book and 2 diamonds on an Arcane inscriber but nothing is happening. I've tried dropping items on it but it's not doing much either.

I understand the bookshelves config now.

Enchanting doesn't work in multiplayer but does work in single player. Being in survival, I've unlocked Smite, have 73 XP levels, many bookshelves around my table (GUI is reporting max enchantment level of 50). When I place a book, a broken iron sword or a fully repaired sword, clicking the enchanted book button doesn't do anything when I'm in SMP.

**Comment by darkhax** [comment] 2015-12-28 23:33
I am not sure about the NEI issue, and I can't reproduce it. I will talk with some other people to see if I can confirm the issue.

The scroll will start to be drawn back, which is a pretty good indicator of how it is meant to be used. The particle effects are mainly meant for other players looking at you, and do not work well in first person, even if the effect did start in front of the player. I will note how to use it in the NEI description though. 

Are you using an enchanted book from vanilla? It should place a book render effect on top of the block. Once you see the render effect, you can place modifiers onto the block. 

In your config, it is set to not allow for the enchanting of broken tools. I can't confirm the GUI issue on servers. I have done a test on the Better Than Minecon test server, which is using RC3, and they do not have this issue.

**Comment by LemADEC** [comment] 2015-12-29 00:08
The particles are showing right when I'm looking a x+1, y+1. If you could adjust the (+1 +1) offset depending player bearing, that would be very neat.

I'm using an vanilla enchanted book. I see no 'rendered' book on the inscriber, it just remains as an half-bookshelf.

Yes, I'm expecting broken tools to be non-enchantable. My issue is that repaired tool aren't either. I guess more testing is needed with less mods involved.

**Comment by darkbumerang** [comment] 2016-02-11 08:00
A question. After enchantment diamond pickaxe on the strength of one, she has a description - "You do not own this item You can not enchant it.." Still I can not enchant. What to do?

**Comment by darkhax** [comment] 2016-02-11 08:34
To document the issue above in greater detail, it is part of a security measure within the mod, to prevent other players from messing with your enchanted tools. This security measure uses the players UUID. The UUID is not reliable if you are using a pirated copy of the game. While we do not endorse pirating the game, it is possible to disable this security measure in the config files, which will solve that issue.

**Comment by darkbumerang** [comment] 2016-02-11 08:37
I am McLaReN. I got a response in the irc chat. ;)

**Closed** 2016-02-20 12:47 UTC
