### ISSUE TITLE
Enchanting Plus only works in creative mode

### ISSUE THREAD

**Issue by Hund** [Epoxide-MC/Enchanting-Plus#13] opened 2015-12-07 04:09 UTC
I'm running my own custom modpack using:

* Enchanting Plus 4.0.0.54 (RC1)
* Bookshelf 1.0.3.138 (I also tried with Bookshelf 1.0.3.145)
* Forge 10.13.4.1558

Adding a tool (I tried with vanilla tools to be sure) didnt show any enchantments. The repair also dont work. The vanilla enchantment table via the Enchanting Plus GUI works though.

If I switch to creative mode it works just fine to add any enchantment to my tools.

**Comment by darkhax** [comment] 2015-12-07 04:13
In enchanting plus 4, players now have to collect and use enchanted scrolls. Each enchanted scroll represents an enchantment, and once unlocked you will be able to use that enchantment as many times as you would like. Scrolls have a 1% chance to drop from any hostile mob. You can also get a scroll from the arcane inscriber by breaking down enchantment books. More specific information can be found [here](http://www.darkhax.net/enchanting-plus-beta.html). The new scroll mode can be disabled in the configuration file, this will give you the old enchantment table behavior.

**Comment by Hund** [comment] 2015-12-07 04:21
Oh! Is this documented somewhere? I thought I've read everything.

I'm sorry for the troubles!

**Comment by darkhax** [comment] 2015-12-07 04:24
@lclc98 and I have taken over the mod, and have rewrote it from scratch. We are currently doing a public beta, to help weed out all of the bugs. This is the version you are currently using. Because this is so new, and technically not released yet, the only documentation for the beta is the stuff written on that page on my site.

**Comment by darkhax** [comment] 2015-12-07 05:03
A tweak was made to the repair cost that should fix any potential issues related to this. 6eac3b5c4de890e170092f5aa9525e269c7fbf8f

**Comment by Hund** [comment] 2015-12-07 06:33
I see. I didn't think of checking the website. Thanks!

**Comment by Hund** [comment] 2015-12-08 04:45
I disabled the "quest mode" in the config and now I cant enchant anything. I also lost the scrolls I added.

**Comment by darkhax** [comment] 2015-12-08 05:42
I can confirm that this configuration option is not working as expected.

**Comment by darkhax** [comment] 2015-12-08 05:52
Thanks for reporting this to us, it has been fixed. The fix will be included in RC2

**Closed** 2015-12-08 05:51 UTC

**Comment by Hund** [comment] 2015-12-08 06:23
Great! :) Is there a ETA on the second RC?

**Comment by darkhax** [comment] 2015-12-08 06:31
We are not 100% sure at this time, however if we can finish up our todo list by tomorrow, then a release for tomorrow will be likely. If we don't do it by then, it might have to wait for a while. Our team is taking a few days off to participate in a game jam. You can download build 64 from [here](https://dl.dropboxusercontent.com/u/38575752/files/EnchantingPlus-1.7.10-4.0.0.64.jar). Build 64 contains all of our changes up until the time of this post.

**Comment by Hund** [comment] 2015-12-08 06:40
Thanks! I'll try it out. :)

**Comment by cjburkey01** [comment] 2016-10-15 20:29
I have disabled questing mode and it still requires scrolls.  Also, how does one use the scrolls?
