### ISSUE TITLE
ID:25 Error Server Crash

### ISSUE THREAD

**Issue by chezpaul** [Epoxide-MC/Enchanting-Plus#10] opened 2015-12-01 17:04 UTC
I got a ID error when launching.
Just went back to 3.0.2
http://pastebin.com/MHrMJbtb

Not sure it's with Emerald mod or biomesOPlenty

**Comment by darkhax** [comment] 2015-12-01 20:09
This is an issue introduced by the Bookshelf dependency. When you have mods that add potions, it's not uncommon to see two or more potions registered under the same ID. Forge and Minecraft do not check for duplicate potion IDs however if you don't resolve them there will be underlying issues with stability. Bookshelf adds code to warn players about this issue so it can be resolved. 

In your specific situation, you are getting this error. Caused by: java.lang.IllegalArgumentException: Duplicate Potion id! EmeraldMod.items.potion.EMPotion and biomesoplenty.common.potions.PotionParalysis Potion ID:25

This means that both mods have a potion which use the ID 25. You will have to go in and change the ID in either of the configuration files. I am going to close this issue, however if you have further questions please feel free to continue comments here.

**Closed by darkhax** 2015-12-01 20:09 UTC
